version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: loan-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - loanpricing-network

  loan-backend:
    build:
      context: ./backend
    container_name: loan-backend
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://loan-mongodb:27017/loan_pricing_db
    networks:
      - loanpricing-network

  loan-frontend:
    build:
      context: ./frontend
    container_name: loan-frontend
    ports:
      - "8080:80"
    depends_on:
      - loan-backend
    networks:
      - loanpricing-network

volumes:
  mongo-data:

networks:
  loanpricing-network:
    driver: bridge
